kubeProxyReplacement: true

l2announcements:
  enabled: true

externalIPs:
  enabled: true

l2podAnnouncements:
  enabled: true
  interface: "eth0"

k8sServiceHost: 192.168.31.101
k8sServicePort: 6443
