---
apiVersion: v1
kind: Namespace
metadata:
  name: nextcloud
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: nextcloud
  namespace: nextcloud
spec:
  storageClassName: nfs-client
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: nextcloud-data
  namespace: nextcloud
spec:
  storageClassName: nfs-client
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 50Gi
