---
kind: Service
apiVersion: v1
metadata:
  name: nextcloud-lb
  namespace: nextcloud
  labels:
    app.kubernetes.io/component: app
    app.kubernetes.io/instance: nextcloud
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: nextcloud
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app.kubernetes.io/component: app
    app.kubernetes.io/instance: nextcloud
    app.kubernetes.io/name: nextcloud
  type: LoadBalancer
  loadBalancerIP: 10.64.1.115
status:
  loadBalancer: {}