kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pg-pvc
  namespace: db
spec:
  storageClassName: nfs-client
  accessModes: 
  - ReadWriteMany
  resources:
    requests:
      storage: 20Gi
